image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
#   SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
#   - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/asset.war

docker-build:
  stage: package
  script:
  - ls -a
  - ls -a target
  - cp target/asset.war docker-preview/
  - cp other/db-init.sql docker-preview/
  - docker build -t asset-preview docker-preview
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/JiangTJ/enterpriseAssetManagement

# k8s-deploy:
#   image: google/cloud-sdk
#   stage: deploy
#   script:
#   - echo "$GOOGLE_KEY" > key.json
#   - gcloud auth activate-service-account --key-file key.json
#   - gcloud config set compute/zone europe-west1-c
#   - gcloud config set project actuator-sample
#   - gcloud config set container/use_client_certificate True
#   - gcloud container clusters get-credentials actuator-sample
#   - kubectl delete secret registry.gitlab.com
#   - kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=marcolenzo --docker-password=$REGISTRY_PASSWD --docker-email=lenzo.marco@gmail.com
#   - kubectl apply -f deployment.yml 
